### ISSUE TITLE
Feature Request: An ability to turn off taking URLs from clipboard

### ISSUE THREAD

**Issue by Karol739** [NickvisionApps/Parabolic#487]
I suggest adding a function to disable taking URLs from clipboard. Clipboard function is used to get URL to a video. Also, in "Add Media" window it should be highlighted in some way that clipboard function is disabled, preferably with a quick link to enabling it back again in settings. For that you may use Adw.Banner, this is how it can look (taken from LibAdwaita's docs): 
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.3/banner-dark.png

Thanks and have a good day!

**Comment by fsobolev** [comment]
Why should it be disabled? If the content of clipboard is not a URL, it will not be pasted, so it's not like it will show your password while you're streaming or something like that.

**Comment by Karol739** [comment]
With this toggle, an app will be more customizable. Also, this function should be quite easy to implement.

**Comment by nlogozzo** [comment]
> With this toggle, an app will be more customizable. Also, this function should be quite easy to implement.

We shouldn't add this just because it's easy and will make it more customizable. 

I agree with @fsobolev . It makes no sense to implement this since only URLs will be pasted (which you probably copied from the video you want to download) and if it's not the correct URL you want to download, just replace it.
