### ISSUE TITLE
[Feature Request] Use of Shift key to select the range of which videos to download

### ISSUE THREAD

**Issue by Nikko-A** [NickvisionApps/Parabolic#498]
Not a necessity, more of a convenience. I would love it if I can just select/deselect a given range of playlist videos with the Shift key. I have tried doing so but it just did not work, unfortunately. Admittedly, this is less of a necessity with the incoming select/deselect button.

**Comment by nlogozzo** [comment]
Will probably have to do what we do in Tagger and use a `Gtk.ListBox` instead of an `Adw.PreferencesGroup`

**Comment by nlogozzo** [comment]
We've tried but we are unable to implement this feature...The problem with turning it into a `Gtk.ListBox` is that each row is a `Adw.EntryRow` which means when you click on a row to select/deselect it, the row will actually take focus so that you can type into it and selection doesn't work.

We also tried just keeping the `Adw.PreferencesGroup` and using a `Gtk.EventControllerKey` to track when and where you press Shift and select but it doesn't handle the Shift key correctly and is giving us issues.

> Admittedly, this is less of a necessity with the incoming select/deselect button.

So this will have to be the solution.
