### ISSUE TITLE
Improvement: Set custom naming rules for files

### ISSUE THREAD

**Issue by Swiftapp-hub** [NickvisionApps/Parabolic#529]
When you download music from YouTube, some have the same title, and it produces an error!
It would be nice to be able to add a random number after the title to allow downloading of music with the same title.
The problem is particularly annoying when downloading playlists with different music, but which have the same title.

Thanks in advance, and I hope I was clear enough! :)

**Comment by fsobolev** [comment]
Note for @nlogozzo:

We could probably change the behavior so instead of raising an error a new file will have ` (N)` suffix in case there's already a file with the same name and overwriting files is disabled.
You can check my code from Cavalier where I implemented adding a suffix if filename exists https://github.com/NickvisionApps/Cavalier/blob/main/NickvisionCavalier.Shared/Controllers/PreferencesViewController.cs#L577

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.1-rc1
