### ISSUE TITLE
Support Upcoming Livestreams

### ISSUE THREAD

**Issue by mecatulo** [NickvisionApps/Parabolic#564]
I just get a message saying the URL is invalid.

**Comment by nlogozzo** [comment]
I mean...if it's an upcoming livestream...there's no video yet, no?

**Comment by fsobolev** [comment]
Sorry, in this universe humanity has just achieved AI, no time traveling yet.

**Comment by nlogozzo** [comment]
Of course we don't mean to make fun. we're just very confused on what you expect from Parabolic...

**Comment by mecatulo** [comment]
> Of course we don't mean to make fun. we're just very confused on what you expect from Parabolic...

ytdlp will just wait if you give it the --wait-for-video flag until the stream is live. I except Parabolic to be able to do the same

**Comment by nlogozzo** [comment]
> > Of course we don't mean to make fun. we're just very confused on what you expect from Parabolic...
> 
> ytdlp will just wait if you give it the --wait-for-video flag until the stream is live. I except Parabolic to be able to do the same

Oh didn't know that was a thing...@fsobolev thoughts? Should we just always pass that flag to yt-dlp since it'll only affect upcoming livestreams

**Comment by fsobolev** [comment]
> @fsobolev thoughts? Should we just always pass that flag to yt-dlp since it'll only affect upcoming livestreams

This flag is not enought. yt-dlp doesn't know (obviously) the list of formats for upcoming streams, so we'll need to detect whether it is a link to an upcoming stream and if yes then only allow best or worst quality.

**Comment by nlogozzo** [comment]
> > @fsobolev thoughts? Should we just always pass that flag to yt-dlp since it'll only affect upcoming livestreams
> 
> This flag is not enought. yt-dlp doesn't know (obviously) the list of formats for upcoming streams, so we'll need to detect whether it is a link to an upcoming stream and if yes then only allow best or worst quality.

We have the whole generic download feature so we can make it do that if it's an upcoming stream,

**Comment by nlogozzo** [comment]
What if we add `--wait-for-video` on just validating? Wouldn't that just cause the dialog to wait for the video and then provide the options for the download and then download?

**Comment by fsobolev** [comment]
> @fsobolev What if we add `--wait-for-video` on just validating? Wouldn't that just cause the dialog to wait for the video and then provide the options for the download and then download?

I suppose that's not what @mecatulo wants. I thought about torrent behaviour, like when you add a torrent, set all options and then it waits if there are no peers. Waiting on validation is useless IMO, because the user needs to interact with the app after the moment a video becomes available to start download.

**Comment by mecatulo** [comment]
@fsobolev it should definitely not need to prompt the user when the livestream starts in order to start the recording. The whole point is to leave it unattended

**Comment by fsobolev** [comment]
Sorry, but unfortunately we aren't going to implement this feature. I tried my best to find a way, but there are just technical limitations. yt-dlp itself can detect upcoming livestream and with `wait_for_video` it can start a timer to wait before actually doing something, but the problem is it doesn't give any info back, there's no reliable way to detect that yt-dlp entered timer mode or just that the URL points to upcoming livestream.
