### ISSUE TITLE
[Feature request] Easier way to add urls to download.

### ISSUE THREAD

**Issue by lb-d** [NickvisionApps/Parabolic#675]
Hi. First of, fantastic program. I have used it daily for some months now as I like to download videos and watch them locally. Maybe not the most common use case. But the experience of downloading many videos isn't great. First you paste the url, then hit validate, wait 4 seconds then hit download. Usually I use the same resolution and download folder so it would be nice if you could set that as a preference and only have to click one button to download a video.

Anyway, thanks for a great program.

**Comment by nlogozzo** [comment]
Hi, that sounds like a useful feature. Just have to think about how we'd implement it design wise. Gonna think about it

**Comment by nlogozzo** [comment]
> First you paste the url, then hit validate, wait 4 seconds then hit download
> Just have to think about how we'd implement it design wise

Because the thing is, Parabolic still needs to validate the video, because validation is what gives Parabolic the supported file types, resolutions, items in the URL, etc...

So at most when you click Validate, Parabolic will take the time to validate, but then will just click Download automatically for you, so what are we really saving doing that?

**Comment by lb-d** [comment]
I see your point. I was thinking setting preferred option in settings so it would download automatically but if the preferences doesn't work (like the site doesn't support resolution or filetype) Then the settings dialog will pop up with an explenation of what it's missing.

But this is absolutely no big deal. Just an idea :)

**Comment by nlogozzo** [comment]
Yeah I mean no need to move it to Preferences since the Add Download dialog already saves your previously used settings and applies them if applicable to new downloads.

So you should just have to click Validate then Download for every download and that's it. I don't think we should try and change this behavior

**Comment by nlogozzo** [comment]
Thanks for the suggestion tho :)
