### ISSUE TITLE
Allow using the nightly version of yt-dlp in the app

### ISSUE THREAD

**Issue by julianfairfax** [NickvisionApps/Parabolic#745]
Not sure exactly how this would be accomplished, but it would be nice, because sometimes the latest release is two months old and doesn't work for the service you're trying to use it (my case right now :(

**Comment by nlogozzo** [comment]
I understand the want of this feature, but as you said I don't know if it is entirely possible.

yt-dlp is bundled into the app when it's built on flatpak/snap/windows. So we can't really introduce a setting that would download the nightly version and use that because like I said it's already bundled into the app from the start.

**Comment by nlogozzo** [comment]
Hopefully, a yt-dlp release will come soon and as soon as it does I will update to it.

**Comment by nlogozzo** [comment]
Working on the update now :)

**Comment by nlogozzo** [comment]
have to wait for flatpak's .NET version to update...should just be an extra day, they are usually pretty fast with it

**Comment by Pentaphon** [comment]
@nlogozzo There's nightly builds for all OS's that are officially distributed at https://github.com/yt-dlp/yt-dlp-nightly-builds/releases so it shouldn't be difficult to use them for the app anymore. Could we have an option on the update page to receive yt-dlp nightly updates? 

@julianfairfax would you like this option as well?

Also there seems to be a new duplicate of this issue at https://github.com/NickvisionApps/Parabolic/issues/1371

**Comment by nlogozzo** [comment]
See #1371 - This will be in the next release
