### ISSUE TITLE
Auto-generated subtitles are not added if native ones are available, even though the option is chosen

### ISSUE THREAD

**Issue by jamal-ali1989** [NickvisionApps/Parabolic#798]
So, the "include auto-generated subtitles" option is active. If the video has no native subtitles, it will download the auto-generated ones. However, if they are available, it will always forego the auto-generated ones. 
I tried just "en" or "eng" or en, eng, en-US, en-CA, en-NZ, en-GB. The results are always the same.
This is the video in question: https://www.youtube.com/watch?v=vDqOoI-4Z6M
This the subtitle language setting: en, eng, en-US, en-CA, en-NZ, en-GB

**Comment by nlogozzo** [comment]
The auto-generated subtitles option is to add auto-gnerated subtitles if native ones are not available. If native ones are available, there is no need for auto-generated subtitles.

If the auto-generated subtitles option is not selected and no native ones are available, no subtitles will be downloaded.

That is the expected behavior of the feature, so I don't really see the issue here.

**Comment by jamal-ali1989** [comment]
I would still prefer to compare them to the native ones sometimes. Is it possible to make it download auto-generated ones even if the native ones are there?

**Comment by nlogozzo** [comment]
A fix for this issue can be found in [V2024.10.0-rc1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.0-rc1).

Please follow the instructions on that page to install this version and test out the fix.

*Please wait an hour after this comment for the update to be pushed to `flathub-beta`*
