### ISSUE TITLE
Restore Generic File Type Selection

### ISSUE THREAD

**Issue by BassBoy320** [NickvisionApps/Parabolic#857]
Hello dear NickvisionApps team,

I discovered that the option for disabling conversion does not exist since the update to the rewritten version.

This option is, in my opinion, very helpful as it does not re-compress the original audio data while also keeping the file as small as possible, because there is no reason for converting a lossy audio stream into a lossless format like FLAC or WAV since the file size increases for like nothing.

A similar issue was created some time ago for the C# version of Parabolic, before it had the _Disallow Conversion_ option: #263 

I appreciate your work. Thanks for Parabolic :+1:

**Comment by nlogozzo** [comment]
Hi! This feature is coming back in the next release soon!

There will be no longer a `Disallow Conversion` option in Preferences, but when selecting a File Type, you will see `Video (Generic)` and `Audio (Generic)` that you can chose instead of a specific file type that will prevent conversions and just download the file as is.

**Comment by nlogozzo** [comment]
This feature is available in today's release! https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.0

*Please allow it some time to be available on Flathub*
