### ISSUE TITLE
QT: Crash When Downloading Videos With Subtitles

### ISSUE THREAD

**Issue by onyto** [NickvisionApps/Parabolic#863]
I just downloaded v2024.10.0 on Windows 11 and tried to download something from YouTube but when I press download the app just closes.
https://www.youtube.com/watch?v=PtvlmOsNV4E or https://www.youtube.com/watch?v=17_uS1DgbFc

Windows 11
v2024.10.0

**Comment by rit001** [comment]
I'm seeing the same issue.

One feature that could help in the future would be the ability for Parabolic to show the command line it will be passing onto yt-dip so that additional debugging can be carried out at the command line.

 All I can say about the error at the moment is that when clicking 'download' within the Add Download panel of Parabolic all that happens is Parabolic closes.

What I can say is that I see the problem on an up-to-date Win11 system (not 24H2) with Parabolic 2024.10.0 that has just been installed.

**Comment by nlogozzo** [comment]
Did either of you have Parabolic installed before V2024.10.0?

What are the download options you are using for each video?

What are the downloader options you have configured in the app's settings? Have you enabled aria2c by any chance?

**Comment by nlogozzo** [comment]
> One feature that could help in the future would be the ability for Parabolic to show the command line it will be passing onto yt-dip so that additional debugging can be carried out at the command line.

This feature is already implemented once the download is added to the list the command is shown. But obviously it's crashing before it's shown in the UI.

**Comment by onyto** [comment]
I just installed it fresh. It crashes with normal downloader and aria2.

**Comment by nlogozzo** [comment]
> I just installed it fresh. It crashes with normal downloader and aria2. It crashes on video downloads and audio only.

The aria2c crash is a known issue (see #860)

What happens if you turn off aria2c?

**Comment by onyto** [comment]
It also crashes with aria2 turned off

**Comment by nlogozzo** [comment]
Okay will investigate.

**Comment by rit001** [comment]
> Did either of you have Parabolic installed before V2024.10.0?
> 
> What are the download options you are using for each video?
> 
> What are the downloader options you have configured in the app's settings? Have you enabled aria2c by any chance?

A clean install on a copy of Windows 11 Pro that was deployed about a year ago.

All settings are at default as I just opened a YouTube page and copied the link into the clipboard which was picked up by Parabolic and placed into the Media URL field. Parabolic can correctly use the link as it gets meta data from YouTube.

**Comment by rit001** [comment]
Odd,  as I was running Parabolic to document the steps for my last post I clicked the Download button and Parabolic this time did download the video, but when I tried another YouTube link it failed and now also fails on the original link.

I have not rebooted my PC or re-logged in since now and when I first posted the issue.

**Comment by nlogozzo** [comment]
Fail as in crashed the application?

I will take a look at the link causing issues and see if I can debug on why it's crashing...

You were downloading as MP4, correct?

**Comment by rit001** [comment]
> Fail as in crashed the application?
> 
> I will take a look at the link causing issues and see if I can debug on why it's crashing...
> 
> You were downloading as MP4, correct?

Yes as I was using all the default settings selected by Parabolic.

**Comment by nlogozzo** [comment]
Found the issue ! Working on a fix...

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*
