### ISSUE TITLE
Dark Theme Missing on Windows 10

### ISSUE THREAD

**Issue by raghavdhingra24** [NickvisionApps/Parabolic#872]
Hi there,
After the recent update and move from WinUI to Qt for the windows build of Parabolic, the dark theme is no longer present on Windows 10 whereas it was present in the previous version. It would be a great if dark mode could be added back.

Parabolic Version: 2024.10.0
Windows Build: 19045.4894

**Comment by nlogozzo** [comment]
Qt uses native Win32 widgets. On Windows 11, the Qt app follows light and dark themes respectively as Microsoft as added support for Win32 dark styles.

Since it's not supported by Win32 natively on Windows 10, it's out of our hands unless Qt sometime in the future backports the Windows 11 theme and style to Windows 10.

See https://forum.qt.io/topic/153241/qt-6-7-beta1-windows11-style-and-windeployqt

**Comment by nlogozzo** [comment]
I could however on Windows 10...set the theme to Fusion...which does respect Windows 10 dark mode.

I will look into it.

**Comment by raghavdhingra24** [comment]
Your suggested idea is great, another idea could be to create a WinUI like stylesheet for Qt which would theme all components used.

**Comment by nlogozzo** [comment]
> another idea could be to create a WinUI like stylesheet for Qt which would theme all components used

I don't really have enough Qt styling knowledge to do this 😅

**Comment by nlogozzo** [comment]
[V2024.10.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.1) is here with a fix for this issue :)

*Allow it some time to be available via Flathub*
