### ISSUE TITLE
Use `Preferred Video Codec` for Playlist Downloads

### ISSUE THREAD

**Issue by KSMaan45** [NickvisionApps/Parabolic#892]
Version 2024.10.1 has no option to select video quality, by default it download highest possible quality 

Version 2024.5.0 from aur with quality options for playlist
![Screenshot from 2024-10-13 21-21-11](https://github.com/user-attachments/assets/9c675316-c1fa-4660-a46a-c6d48106ba52)

Version 2024.10.1 from flathub with missing quality selection option for playlist
![Screenshot from 2024-10-13 21-22-12](https://github.com/user-attachments/assets/9c9a5310-54f4-4dae-a22b-450431e3f75a)

**Comment by nlogozzo** [comment]
So, this option was removed because it was implemented in a hacky way. 

`yt-dlp` provides 2 modes for getting playlist information. A `flat` mode and a `normal` mode.

The `flat` mode provides:
- The name of the playlist
- Each item in the playlist with its title and URL to download

The `normal` mode provides:
- The name of the playlist
- Each item in the playlist with its title, URL, video resolution, subtitles, audio languages (all the information provided when you download a single video)

For the `normal` mode, however, to get all of this information for each item in the playlist, it needs to validate and fetch each item in the playlist individually. For a playlist with 100 items or even simply 10 items, this can take a long time. Anywhere from 2-5 minutes, sometimes even longer.

Therefore, to avoid this long wait in both V2024.5.0 and V2024.10.0 we've always used `flat` mode for playlists.

However, in V2024.5.0 we would separately ourselves validate only the first item in the playlist to get the `Maximum Resolution`, `Audio Language` and `Subtitles` options you see in the first screenshot when validating a playlist. However, this is simply just wrong. Because we can't assume from the first video that the rest of the videos in the playlist will have the same resolutions, languages, and subtitles. 

Thus, we no longer validate the first playlist item in V2024.10.0 due to lack of a better/faster way to get this information from yt-dlp while still using `flat` mode.

**Comment by KSMaan45** [comment]
So flat mode can't use our prefer codecs? Since it download highest resolution with vp9 codec while the preferred one are h264 in settings, with preferred codec h264 maximum resolution mostly like be 1080p while if h264 was not available it can fallback to vp9 for that specific video in playlist if possible that might sort few things just an idea tho...

**Comment by nlogozzo** [comment]
> So flat mode can't use our prefer codecs? Since it download highest resolution with vp9 codec while the preferred one are h264 in settings, with preferred codec h264 maximum resolution mostly like be 1080p while if h264 was not available it can fallback to vp9 for that specific video in playlist if possible that might sort few things just an idea tho...

Yeah it's hard to do because when we get a `VideoResolution` we get the `Width x Height` (i.e. 1920x1080) and the `Codec` and then after you select a resolution, `Parabolic` will take that and your preferred codec into account and pick the correct version of the video to download...that's how it works for individual (single) downloads.

But again, with playlists and `flat` mode, we get no resolution information at all.

What I might be able to do however is use `yt-dlp`'s `--format-sort` option. This **should** allow me to provide suggestions on what is considered the "best"/"highest" resolution to download, and I can provide it with your preferred codec.

I will look into it....

**Comment by nlogozzo** [comment]
[V2024.10.2](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.10.2) is here with a fix for this issue!
