### ISSUE TITLE
Crash File Name Too Long + Infinite Recovery Mode Loop

### ISSUE THREAD

**Issue by Francehelder** [NickvisionApps/Parabolic#928]
I tried to download a TikTok video, when Parabolic crashed and now it refuses to open.

Link of the video: https://vm.tiktok.com/ZMhQMtwsV/

Terminal output:

![image](https://github.com/user-attachments/assets/5d73392a-a847-48be-8146-3f962da9b385)

**Comment by nlogozzo** [comment]
So, we have 2 issues here.

1) The app is crashing because the `file name` is too long
2) The app will not open because of the recovery mode feature in V2024.10.3 that is trying to restart the download but it crashes again because of (1)

What you need to do is go into this folder: `~/.var/app/org.nickvision.tubeconverter/config/Nickvision Parabolic` and delete the `recovery.json` file.

I will try to fix both of these issues.

**Comment by nlogozzo** [comment]
Can you provide me with the URL you were trying to download?

**Comment by Francehelder** [comment]
> Can you provide me with the URL you were trying to download?

It's already in this post

**Comment by nlogozzo** [comment]
> > Can you provide me with the URL you were trying to download?
> 
> It's already in this post

Ah missed it. Thank you!

**Comment by nlogozzo** [comment]
This fix is available in today's release! https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.0

*Please allow it some time to be available on Flathub*
