### ISSUE TITLE
External subtitle files are always created, although "embed subtitles" is enabled

### ISSUE THREAD

**Issue by sojusnik** [NickvisionApps/Parabolic#943]
Although "embed subtitles" is enabled, which does embed subtitles into a file, external subtitle files appear as well (always as .vtt), which is an unnecessary and confusing redundancy.

When downloading a file, I have 3 automatically generated subtitles selected.

Preferred subtitle format: generic
Include automatically generated subtitles: on

Troubleshooting:
```
org.nickvision.tubeconverter
Linux
2024.11.0

Deployment Mode: Flatpak
Locale: de_DE.UTF-8
Running From: "/app/lib/org.nickvision.tubeconverter"

yt-dlp version 2024.11.04
ffmpeg version 7.1 
aria2 Version 1.37.0

GTK 4.16.3
libadwaita 1.6.1

LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

**Comment by nlogozzo** [comment]
[V2024.11.1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.11.1) is here with a fix for this issue!

**Comment by nlogozzo** [comment]
See https://github.com/NickvisionApps/Parabolic/issues/1042#issuecomment-2610573937

**Comment by nlogozzo** [comment]
>  because in previous versions (before the bigger upgrade to the new UI) the subtitles were embedded even when generic video was selected.

That's because Parabolic incorrectly assumed embedding was supported in the past. 

However, there where some times in which the generic download would fail because it would download a file type that does not support embedding and would try to embed to yt-dlp would complain.

> Is there really nothing you could do, since currently you are forced to specify a video format for embedded subtitles, losing the ability to download the original video file?

No. That's the drawback of using generic videos. Almost all generic YouTube videos result in a `webm` file. And `webm` DOES NOT support embedding subtitles and thumbnails. 

Therefore, it's either you select `MP4` so it will convert the file and then be able to embed the thumbnail and subtitles OR Parabolic will assume it's supported and then sometimes `yt-dlp` will either fail or will automatically convert the `webm` file to lets say a `MKV` file that does support embedding. So either way you loose the original file.
